# Generated by Django 5.1.2 on 2024-10-19 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.TextField(max_length=10, unique=True)),
                ('password', models.CharField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('role', models.TextField(default='USER')),
            ],
        ),
    ]
