# Generated by Django 5.1.1 on 2024-11-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appointment_doctor_remove_appointment_patient'),
        ('billings', '0003_remove_bill_patient'),
        ('department', '0003_remove_department_head_doctor'),
        ('medical_records', '0003_remove_medicalrecord_doctor_and_more'),
        ('users', '0003_alter_doctor_availability_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('admin', 'Administrator'), ('user', 'user')], default='user'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
