# Generated by Django 5.1.1 on 2024-11-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='patient',
        ),
    ]
