# Generated by Django 5.1.1 on 2024-10-24 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('users', '0002_doctor_nurse_patient_user_delete_users_patient_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='departments',
            field=models.ManyToManyField(to='department.department'),
        ),
    ]
