# Generated by Django 5.1.1 on 2024-11-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='head_doctor',
        ),
    ]
